package com.pq.tracs.model.lookups;

import com.pq.tracs.model.dao.TracsView;

import java.math.BigDecimal;

import oracle.jbo.domain.Number;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ContractContactROViewImpl extends TracsView {
    /**This is the default constructor (do not remove)
     */
    public ContractContactROViewImpl() {
    }


    protected void create() {
        super.create();
        setManageRowsByKey(true);
    }


    /**
     * Returns the bind variable value for CONTENT_OWNER_ID.
     * @return bind variable value for CONTENT_OWNER_ID
     */
    public Number getCONTENT_OWNER_ID() {
        return (Number)getNamedWhereClauseParam("CONTENT_OWNER_ID");
    }

    /**
     * Sets <code>value</code> for bind variable CONTENT_OWNER_ID.
     * @param value value to bind as CONTENT_OWNER_ID
     */
    public void setCONTENT_OWNER_ID(Number value) {
        setNamedWhereClauseParam("CONTENT_OWNER_ID", value);
    }
}
