package com.pq.tracs.model.vo;

import com.pq.tracs.model.dao.TracsView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 26 15:26:04 EDT 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PrmOpportunityAgreementDataViewImpl extends TracsView {
    /**
     * This is the default constructor (do not remove).
     */
    public PrmOpportunityAgreementDataViewImpl() {
    }
}
