package com.pq.tracs.model.dao;

import com.pq.tracs.model.bo.ContentOwnerImpl;
import com.pq.tracs.model.bo.ContractTitleImpl;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 08 12:15:08 EST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ContractTitleViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CatalogNumber {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getCatalogNumber();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setCatalogNumber((String)value);
            }
        }
        ,
        ShortTitle {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getShortTitle();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setShortTitle((String)value);
            }
        }
        ,
        Name {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getName();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setName((String)value);
            }
        }
        ,
        PublicationStartYear {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getPublicationStartYear();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setPublicationStartYear((String)value);
            }
        }
        ,
        PublicationEndYear {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getPublicationEndYear();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setPublicationEndYear((String)value);
            }
        }
        ,
        EffectiveDate {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getEffectiveDate();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setEffectiveDate((Date)value);
            }
        }
        ,
        ExpiresDate {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getExpiresDate();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setExpiresDate((Date)value);
            }
        }
        ,
        Status {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getStatus();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        SubStatus {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getSubStatus();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setSubStatus((String)value);
            }
        }
        ,
        BackfileFromDate {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getBackfileFromDate();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setBackfileFromDate((Date)value);
            }
        }
        ,
        BackfileToDate {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getBackfileToDate();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setBackfileToDate((Date)value);
            }
        }
        ,
        BackfileViaEfeedFlag {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getBackfileViaEfeedFlag();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setBackfileViaEfeedFlag((String)value);
            }
        }
        ,
        EfeedDateAvailable {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getEfeedDateAvailable();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setEfeedDateAvailable((Date)value);
            }
        }
        ,
        EfeedFlag {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getEfeedFlag();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setEfeedFlag((String)value);
            }
        }
        ,
        EfeedProtocolChangeDays {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getEfeedProtocolChangeDays();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setEfeedProtocolChangeDays((Number)value);
            }
        }
        ,
        ExceptionFlag {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getExceptionFlag();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setExceptionFlag((String)value);
            }
        }
        ,
        Exclusivity {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getExclusivity();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setExclusivity((String)value);
            }
        }
        ,
        RemovalDate {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getRemovalDate();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setRemovalDate((Date)value);
            }
        }
        ,
        RightsToBeRetained {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getRightsToBeRetained();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setRightsToBeRetained((String)value);
            }
        }
        ,
        VolumeYearStart {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getVolumeYearStart();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setVolumeYearStart((String)value);
            }
        }
        ,
        VolumeYearEnd {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getVolumeYearEnd();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setVolumeYearEnd((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreatedDate {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setCreatedDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        Id {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getId();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setId((Number)value);
            }
        }
        ,
        ContractId {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getContractId();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setContractId((Number)value);
            }
        }
        ,
        TitleId {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getTitleId();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setTitleId((Number)value);
            }
        }
        ,
        Id1 {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getId1();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setId1((Number)value);
            }
        }
        ,
        LongTitle {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getLongTitle();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setLongTitle((String)value);
            }
        }
        ,
        Id2 {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getId2();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setId2((Number)value);
            }
        }
        ,
        ContentOwnerId {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getContentOwnerId();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setContentOwnerId((Number)value);
            }
        }
        ,
        TargetTrackingNo {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getTargetTrackingNo();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setTargetTrackingNo((Number)value);
            }
        }
        ,
        PrimaryClassification {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getPrimaryClassification();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setPrimaryClassification((String)value);
            }
        }
        ,
        LastUpdatedDate1 {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getLastUpdatedDate1();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setLastUpdatedDate1((Date)value);
            }
        }
        ,
        ContentOwnerCount {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getContentOwnerCount();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setContentOwnerCount((Number)value);
            }
        }
        ,
        JContractTitleContractRightView {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getJContractTitleContractRightView();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ContentOwnerTitlesLookup {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getContentOwnerTitlesLookup();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ContractTitleRoyaltyRateView {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getContractTitleRoyaltyRateView();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ContractView {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getContractView();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ContractExclusivityLookup {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getContractExclusivityLookup();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ContractRightSetLookup {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getContractRightSetLookup();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ContractTitleStatusLookup {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getContractTitleStatusLookup();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ContractTitleSubStatusLookup {
            public Object get(ContractTitleViewRowImpl obj) {
                return obj.getContractTitleSubStatusLookup();
            }

            public void put(ContractTitleViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(ContractTitleViewRowImpl object);

        public abstract void put(ContractTitleViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CATALOGNUMBER = AttributesEnum.CatalogNumber.index();
    public static final int SHORTTITLE = AttributesEnum.ShortTitle.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int PUBLICATIONSTARTYEAR = AttributesEnum.PublicationStartYear.index();
    public static final int PUBLICATIONENDYEAR = AttributesEnum.PublicationEndYear.index();
    public static final int EFFECTIVEDATE = AttributesEnum.EffectiveDate.index();
    public static final int EXPIRESDATE = AttributesEnum.ExpiresDate.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int SUBSTATUS = AttributesEnum.SubStatus.index();
    public static final int BACKFILEFROMDATE = AttributesEnum.BackfileFromDate.index();
    public static final int BACKFILETODATE = AttributesEnum.BackfileToDate.index();
    public static final int BACKFILEVIAEFEEDFLAG = AttributesEnum.BackfileViaEfeedFlag.index();
    public static final int EFEEDDATEAVAILABLE = AttributesEnum.EfeedDateAvailable.index();
    public static final int EFEEDFLAG = AttributesEnum.EfeedFlag.index();
    public static final int EFEEDPROTOCOLCHANGEDAYS = AttributesEnum.EfeedProtocolChangeDays.index();
    public static final int EXCEPTIONFLAG = AttributesEnum.ExceptionFlag.index();
    public static final int EXCLUSIVITY = AttributesEnum.Exclusivity.index();
    public static final int REMOVALDATE = AttributesEnum.RemovalDate.index();
    public static final int RIGHTSTOBERETAINED = AttributesEnum.RightsToBeRetained.index();
    public static final int VOLUMEYEARSTART = AttributesEnum.VolumeYearStart.index();
    public static final int VOLUMEYEAREND = AttributesEnum.VolumeYearEnd.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int ID = AttributesEnum.Id.index();
    public static final int CONTRACTID = AttributesEnum.ContractId.index();
    public static final int TITLEID = AttributesEnum.TitleId.index();
    public static final int ID1 = AttributesEnum.Id1.index();
    public static final int LONGTITLE = AttributesEnum.LongTitle.index();
    public static final int ID2 = AttributesEnum.Id2.index();
    public static final int CONTENTOWNERID = AttributesEnum.ContentOwnerId.index();
    public static final int TARGETTRACKINGNO = AttributesEnum.TargetTrackingNo.index();
    public static final int PRIMARYCLASSIFICATION = AttributesEnum.PrimaryClassification.index();
    public static final int LASTUPDATEDDATE1 = AttributesEnum.LastUpdatedDate1.index();
    public static final int CONTENTOWNERCOUNT = AttributesEnum.ContentOwnerCount.index();
    public static final int JCONTRACTTITLECONTRACTRIGHTVIEW = AttributesEnum.JContractTitleContractRightView.index();
    public static final int CONTENTOWNERTITLESLOOKUP = AttributesEnum.ContentOwnerTitlesLookup.index();
    public static final int CONTRACTTITLEROYALTYRATEVIEW = AttributesEnum.ContractTitleRoyaltyRateView.index();
    public static final int CONTRACTVIEW = AttributesEnum.ContractView.index();
    public static final int CONTRACTEXCLUSIVITYLOOKUP = AttributesEnum.ContractExclusivityLookup.index();
    public static final int CONTRACTRIGHTSETLOOKUP = AttributesEnum.ContractRightSetLookup.index();
    public static final int CONTRACTTITLESTATUSLOOKUP = AttributesEnum.ContractTitleStatusLookup.index();
    public static final int CONTRACTTITLESUBSTATUSLOOKUP = AttributesEnum.ContractTitleSubStatusLookup.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ContractTitleViewRowImpl() {
    }

    /**
     * Gets ContractTitle entity object.
     * @return the ContractTitle
     */
    public ContractTitleImpl getContractTitle() {
        return (ContractTitleImpl)getEntity(0);
    }

    /**
     * Gets Title entity object.
     * @return the Title
     */
    public com.pq.tracs.model.bo.TitleImpl getTitle() {
        return (com.pq.tracs.model.bo.TitleImpl)getEntity(1);
    }

    /**
     * Gets ContentOwner entity object.
     * @return the ContentOwner
     */
    public ContentOwnerImpl getContentOwner() {
        return (ContentOwnerImpl)getEntity(2);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public Number getId() {
        return (Number)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for CONTRACT_ID using the alias name ContractId.
     * @return the CONTRACT_ID
     */
    public Number getContractId() {
        return (Number)getAttributeInternal(CONTRACTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_ID using the alias name ContractId.
     * @param value value to set the CONTRACT_ID
     */
    public void setContractId(Number value) {
        setAttributeInternal(CONTRACTID, value);
    }

    /**
     * Gets the attribute value for TITLE_ID using the alias name TitleId.
     * @return the TITLE_ID
     */
    public Number getTitleId() {
        return (Number)getAttributeInternal(TITLEID);
    }

    /**
     * Sets <code>value</code> as attribute value for TITLE_ID using the alias name TitleId.
     * @param value value to set the TITLE_ID
     */
    public void setTitleId(Number value) {
        setAttributeInternal(TITLEID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date)getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for EFFECTIVE_DATE using the alias name EffectiveDate.
     * @return the EFFECTIVE_DATE
     */
    public Date getEffectiveDate() {
        return (Date)getAttributeInternal(EFFECTIVEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EFFECTIVE_DATE using the alias name EffectiveDate.
     * @param value value to set the EFFECTIVE_DATE
     */
    public void setEffectiveDate(Date value) {
        setAttributeInternal(EFFECTIVEDATE, value);
    }

    /**
     * Gets the attribute value for EXPIRES_DATE using the alias name ExpiresDate.
     * @return the EXPIRES_DATE
     */
    public Date getExpiresDate() {
        return (Date)getAttributeInternal(EXPIRESDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPIRES_DATE using the alias name ExpiresDate.
     * @param value value to set the EXPIRES_DATE
     */
    public void setExpiresDate(Date value) {
        setAttributeInternal(EXPIRESDATE, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
        if (value != null && value.equalsIgnoreCase("Removed")) {
          this.setRemovalDate(new Date(Date.getCurrentDate()));
        } else {
          this.setRemovalDate(null);
        }
    }

    /**
     * Gets the attribute value for SUB_STATUS using the alias name SubStatus.
     * @return the SUB_STATUS
     */
    public String getSubStatus() {
        return (String) getAttributeInternal(SUBSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for SUB_STATUS using the alias name SubStatus.
     * @param value value to set the SUB_STATUS
     */
    public void setSubStatus(String value) {
        setAttributeInternal(SUBSTATUS, value);
    }

    /**
     * Gets the attribute value for BACKFILE_FROM_DATE using the alias name BackfileFromDate.
     * @return the BACKFILE_FROM_DATE
     */
    public Date getBackfileFromDate() {
        return (Date)getAttributeInternal(BACKFILEFROMDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for BACKFILE_FROM_DATE using the alias name BackfileFromDate.
     * @param value value to set the BACKFILE_FROM_DATE
     */
    public void setBackfileFromDate(Date value) {
        setAttributeInternal(BACKFILEFROMDATE, value);
    }

    /**
     * Gets the attribute value for BACKFILE_TO_DATE using the alias name BackfileToDate.
     * @return the BACKFILE_TO_DATE
     */
    public Date getBackfileToDate() {
        return (Date)getAttributeInternal(BACKFILETODATE);
    }

    /**
     * Sets <code>value</code> as attribute value for BACKFILE_TO_DATE using the alias name BackfileToDate.
     * @param value value to set the BACKFILE_TO_DATE
     */
    public void setBackfileToDate(Date value) {
        setAttributeInternal(BACKFILETODATE, value);
    }

    /**
     * Gets the attribute value for BACKFILE_VIA_EFEED_FLAG using the alias name BackfileViaEfeedFlag.
     * @return the BACKFILE_VIA_EFEED_FLAG
     */
    public String getBackfileViaEfeedFlag() {
        return (String) getAttributeInternal(BACKFILEVIAEFEEDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for BACKFILE_VIA_EFEED_FLAG using the alias name BackfileViaEfeedFlag.
     * @param value value to set the BACKFILE_VIA_EFEED_FLAG
     */
    public void setBackfileViaEfeedFlag(String value) {
        setAttributeInternal(BACKFILEVIAEFEEDFLAG, value);
    }

    /**
     * Gets the attribute value for EFEED_DATE_AVAILABLE using the alias name EfeedDateAvailable.
     * @return the EFEED_DATE_AVAILABLE
     */
    public Date getEfeedDateAvailable() {
        return (Date)getAttributeInternal(EFEEDDATEAVAILABLE);
    }

    /**
     * Sets <code>value</code> as attribute value for EFEED_DATE_AVAILABLE using the alias name EfeedDateAvailable.
     * @param value value to set the EFEED_DATE_AVAILABLE
     */
    public void setEfeedDateAvailable(Date value) {
        setAttributeInternal(EFEEDDATEAVAILABLE, value);
    }

    /**
     * Gets the attribute value for EFEED_FLAG using the alias name EfeedFlag.
     * @return the EFEED_FLAG
     */
    public String getEfeedFlag() {
        return (String) getAttributeInternal(EFEEDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for EFEED_FLAG using the alias name EfeedFlag.
     * @param value value to set the EFEED_FLAG
     */
    public void setEfeedFlag(String value) {
        setAttributeInternal(EFEEDFLAG, value);
    }

    /**
     * Gets the attribute value for EFEED_PROTOCOL_CHANGE_DAYS using the alias name EfeedProtocolChangeDays.
     * @return the EFEED_PROTOCOL_CHANGE_DAYS
     */
    public Number getEfeedProtocolChangeDays() {
        return (Number)getAttributeInternal(EFEEDPROTOCOLCHANGEDAYS);
    }

    /**
     * Sets <code>value</code> as attribute value for EFEED_PROTOCOL_CHANGE_DAYS using the alias name EfeedProtocolChangeDays.
     * @param value value to set the EFEED_PROTOCOL_CHANGE_DAYS
     */
    public void setEfeedProtocolChangeDays(Number value) {
        setAttributeInternal(EFEEDPROTOCOLCHANGEDAYS, value);
    }

    /**
     * Gets the attribute value for EXCEPTION_FLAG using the alias name ExceptionFlag.
     * @return the EXCEPTION_FLAG
     */
    public String getExceptionFlag() {
        return (String) getAttributeInternal(EXCEPTIONFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for EXCEPTION_FLAG using the alias name ExceptionFlag.
     * @param value value to set the EXCEPTION_FLAG
     */
    public void setExceptionFlag(String value) {
        setAttributeInternal(EXCEPTIONFLAG, value);
    }

    /**
     * Gets the attribute value for EXCLUSIVITY using the alias name Exclusivity.
     * @return the EXCLUSIVITY
     */
    public String getExclusivity() {
        return (String) getAttributeInternal(EXCLUSIVITY);
    }

    /**
     * Sets <code>value</code> as attribute value for EXCLUSIVITY using the alias name Exclusivity.
     * @param value value to set the EXCLUSIVITY
     */
    public void setExclusivity(String value) {
        setAttributeInternal(EXCLUSIVITY, value);
    }

    /**
     * Gets the attribute value for REMOVAL_DATE using the alias name RemovalDate.
     * @return the REMOVAL_DATE
     */
    public Date getRemovalDate() {
        return (Date)getAttributeInternal(REMOVALDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for REMOVAL_DATE using the alias name RemovalDate.
     * @param value value to set the REMOVAL_DATE
     */
    public void setRemovalDate(Date value) {
        setAttributeInternal(REMOVALDATE, value);
    }

    /**
     * Gets the attribute value for RIGHTS_TO_BE_RETAINED using the alias name RightsToBeRetained.
     * @return the RIGHTS_TO_BE_RETAINED
     */
    public String getRightsToBeRetained() {
        return (String) getAttributeInternal(RIGHTSTOBERETAINED);
    }

    /**
     * Sets <code>value</code> as attribute value for RIGHTS_TO_BE_RETAINED using the alias name RightsToBeRetained.
     * @param value value to set the RIGHTS_TO_BE_RETAINED
     */
    public void setRightsToBeRetained(String value) {
        setAttributeInternal(RIGHTSTOBERETAINED, value);
    }

    /**
     * Gets the attribute value for VOLUME_YEAR_END using the alias name VolumeYearEnd.
     * @return the VOLUME_YEAR_END
     */
    public String getVolumeYearEnd() {
        return (String) getAttributeInternal(VOLUMEYEAREND);
    }

    /**
     * Sets <code>value</code> as attribute value for VOLUME_YEAR_END using the alias name VolumeYearEnd.
     * @param value value to set the VOLUME_YEAR_END
     */
    public void setVolumeYearEnd(String value) {
        setAttributeInternal(VOLUMEYEAREND, value);
    }

    /**
     * Gets the attribute value for VOLUME_YEAR_START using the alias name VolumeYearStart.
     * @return the VOLUME_YEAR_START
     */
    public String getVolumeYearStart() {
        return (String) getAttributeInternal(VOLUMEYEARSTART);
    }

    /**
     * Sets <code>value</code> as attribute value for VOLUME_YEAR_START using the alias name VolumeYearStart.
     * @param value value to set the VOLUME_YEAR_START
     */
    public void setVolumeYearStart(String value) {
        setAttributeInternal(VOLUMEYEARSTART, value);
    }

    /**
     * Gets the attribute value for ID using the alias name Id1.
     * @return the ID
     */
    public Number getId1() {
        return (Number)getAttributeInternal(ID1);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id1.
     * @param value value to set the ID
     */
    public void setId1(Number value) {
        setAttributeInternal(ID1, value);
    }

    /**
     * Gets the attribute value for CONTENT_OWNER_ID using the alias name ContentOwnerId.
     * @return the CONTENT_OWNER_ID
     */
    public Number getContentOwnerId() {
        return (Number)getAttributeInternal(CONTENTOWNERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTENT_OWNER_ID using the alias name ContentOwnerId.
     * @param value value to set the CONTENT_OWNER_ID
     */
    public void setContentOwnerId(Number value) {
        setAttributeInternal(CONTENTOWNERID, value);
    }

    /**
     * Gets the attribute value for TARGET_TRACKING_NO using the alias name TargetTrackingNo.
     * @return the TARGET_TRACKING_NO
     */
    public Number getTargetTrackingNo() {
        return (Number)getAttributeInternal(TARGETTRACKINGNO);
    }

    /**
     * Sets <code>value</code> as attribute value for TARGET_TRACKING_NO using the alias name TargetTrackingNo.
     * @param value value to set the TARGET_TRACKING_NO
     */
    public void setTargetTrackingNo(Number value) {
        setAttributeInternal(TARGETTRACKINGNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrimaryClassification.
     * @return the PrimaryClassification
     */
    public String getPrimaryClassification() {
        return (String) getAttributeInternal(PRIMARYCLASSIFICATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrimaryClassification.
     * @param value value to set the  PrimaryClassification
     */
    public void setPrimaryClassification(String value) {
        setAttributeInternal(PRIMARYCLASSIFICATION, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate1.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate1() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE1);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate1.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate1(Date value) {
        setAttributeInternal(LASTUPDATEDDATE1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ContentOwnerCount.
     * @return the ContentOwnerCount
     */
    public Number getContentOwnerCount() {
        return (Number)getAttributeInternal(CONTENTOWNERCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ContentOwnerCount.
     * @param value value to set the  ContentOwnerCount
     */
    public void setContentOwnerCount(Number value) {
        setAttributeInternal(CONTENTOWNERCOUNT, value);
    }

    /**
     * Gets the attribute value for LONG_TITLE using the alias name LongTitle.
     * @return the LONG_TITLE
     */
    public String getLongTitle() {
        return (String) getAttributeInternal(LONGTITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for LONG_TITLE using the alias name LongTitle.
     * @param value value to set the LONG_TITLE
     */
    public void setLongTitle(String value) {
        setAttributeInternal(LONGTITLE, value);
    }

    /**
     * Gets the attribute value for CATALOG_NUMBER using the alias name CatalogNumber.
     * @return the CATALOG_NUMBER
     */
    public String getCatalogNumber() {
        return (String) getAttributeInternal(CATALOGNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for CATALOG_NUMBER using the alias name CatalogNumber.
     * @param value value to set the CATALOG_NUMBER
     */
    public void setCatalogNumber(String value) {
        setAttributeInternal(CATALOGNUMBER, value);
    }


    /**
     * Gets the attribute value for PUBLICATION_START_YEAR using the alias name PublicationStartYear.
     * @return the PUBLICATION_START_YEAR
     */
    public String getPublicationStartYear() {
        return (String) getAttributeInternal(PUBLICATIONSTARTYEAR);
    }

    /**
     * Sets <code>value</code> as attribute value for PUBLICATION_START_YEAR using the alias name PublicationStartYear.
     * @param value value to set the PUBLICATION_START_YEAR
     */
    public void setPublicationStartYear(String value) {
        setAttributeInternal(PUBLICATIONSTARTYEAR, value);
    }

    /**
     * Gets the attribute value for PUBLICATION_END_YEAR using the alias name PublicationEndYear.
     * @return the PUBLICATION_END_YEAR
     */
    public String getPublicationEndYear() {
        return (String) getAttributeInternal(PUBLICATIONENDYEAR);
    }

    /**
     * Sets <code>value</code> as attribute value for PUBLICATION_END_YEAR using the alias name PublicationEndYear.
     * @param value value to set the PUBLICATION_END_YEAR
     */
    public void setPublicationEndYear(String value) {
        setAttributeInternal(PUBLICATIONENDYEAR, value);
    }

    /**
     * Gets the attribute value for SHORT_TITLE using the alias name ShortTitle.
     * @return the SHORT_TITLE
     */
    public String getShortTitle() {
        return (String) getAttributeInternal(SHORTTITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for SHORT_TITLE using the alias name ShortTitle.
     * @param value value to set the SHORT_TITLE
     */
    public void setShortTitle(String value) {
        setAttributeInternal(SHORTTITLE, value);
    }


    /**
     * Gets the attribute value for NAME using the alias name Name.
     * @return the NAME
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME using the alias name Name.
     * @param value value to set the NAME
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for ID using the alias name Id2.
     * @return the ID
     */
    public Number getId2() {
        return (Number)getAttributeInternal(ID2);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id2.
     * @param value value to set the ID
     */
    public void setId2(Number value) {
        setAttributeInternal(ID2, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link JContractTitleContractRightView.
     */
    public RowIterator getJContractTitleContractRightView() {
        return (RowIterator)getAttributeInternal(JCONTRACTTITLECONTRACTRIGHTVIEW);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link ContentOwnerTitlesLookup.
     */
    public Row getContentOwnerTitlesLookup() {
        return (Row)getAttributeInternal(CONTENTOWNERTITLESLOOKUP);
    }

    /**
     * Sets the master-detail link ContentOwnerTitlesLookup between this object and <code>value</code>.
     */
    public void setContentOwnerTitlesLookup(Row value) {
        setAttributeInternal(CONTENTOWNERTITLESLOOKUP, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ContractTitleRoyaltyRateView.
     */
    public RowIterator getContractTitleRoyaltyRateView() {
        return (RowIterator)getAttributeInternal(CONTRACTTITLEROYALTYRATEVIEW);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link ContractView.
     */
    public Row getContractView() {
        return (Row)getAttributeInternal(CONTRACTVIEW);
    }

    /**
     * Sets the master-detail link ContractView between this object and <code>value</code>.
     */
    public void setContractView(Row value) {
        setAttributeInternal(CONTRACTVIEW, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ContractExclusivityLookup.
     */
    public RowSet getContractExclusivityLookup() {
        return (RowSet)getAttributeInternal(CONTRACTEXCLUSIVITYLOOKUP);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ContractRightSetLookup.
     */
    public RowSet getContractRightSetLookup() {
        return (RowSet)getAttributeInternal(CONTRACTRIGHTSETLOOKUP);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ContractTitleStatusLookup.
     */
    public RowSet getContractTitleStatusLookup() {
        return (RowSet)getAttributeInternal(CONTRACTTITLESTATUSLOOKUP);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ContractTitleSubStatusLookup.
     */
    public RowSet getContractTitleSubStatusLookup() {
        return (RowSet)getAttributeInternal(CONTRACTTITLESUBSTATUSLOOKUP);
    }


    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
