package com.pq.tracs.model.dao;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 24 11:52:09 EST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OvrBrowseTypeViewImpl extends TracsView {
    /**
     * This is the default constructor (do not remove).
     */
    public OvrBrowseTypeViewImpl() {
    }
}
