package com.pq.tracs.model.dao;

import com.pq.tracs.model.bo.RoyaltyRateImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.TransactionEvent;
import oracle.jbo.server.ViewRowImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RoyaltyRateViewRowImpl extends ViewRowImpl {
    public static final int ROYALTYRATE1_1_1 = 4;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(RoyaltyRateViewRowImpl obj) {
                return obj.getId();
            }

            public void put(RoyaltyRateViewRowImpl obj, Object value) {
                obj.setId((Number)value);
            }
        }
        ,
        ContractId {
            public Object get(RoyaltyRateViewRowImpl obj) {
                return obj.getContractId();
            }

            public void put(RoyaltyRateViewRowImpl obj, Object value) {
                obj.setContractId((Number)value);
            }
        }
        ,
        Media {
            public Object get(RoyaltyRateViewRowImpl obj) {
                return obj.getMedia();
            }

            public void put(RoyaltyRateViewRowImpl obj, Object value) {
                obj.setMedia((String)value);
            }
        }
        ,
        RateType {
            public Object get(RoyaltyRateViewRowImpl obj) {
                return obj.getRateType();
            }

            public void put(RoyaltyRateViewRowImpl obj, Object value) {
                obj.setRateType((String)value);
            }
        }
        ,
        RoyaltyRate1 {
            public Object get(RoyaltyRateViewRowImpl obj) {
                return obj.getRoyaltyRate1();
            }

            public void put(RoyaltyRateViewRowImpl obj, Object value) {
                obj.setRoyaltyRate1((Number)value);
            }
        }
        ,
        EffectiveStartDate {
            public Object get(RoyaltyRateViewRowImpl obj) {
                return obj.getEffectiveStartDate();
            }

            public void put(RoyaltyRateViewRowImpl obj, Object value) {
                obj.setEffectiveStartDate((Date)value);
            }
        }
        ,
        EffectiveEndDate {
            public Object get(RoyaltyRateViewRowImpl obj) {
                return obj.getEffectiveEndDate();
            }

            public void put(RoyaltyRateViewRowImpl obj, Object value) {
                obj.setEffectiveEndDate((Date)value);
            }
        }
        ,
        ExceptionFlag {
            public Object get(RoyaltyRateViewRowImpl obj) {
                return obj.getExceptionFlag();
            }

            public void put(RoyaltyRateViewRowImpl obj, Object value) {
                obj.setExceptionFlag((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(RoyaltyRateViewRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(RoyaltyRateViewRowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreatedDate {
            public Object get(RoyaltyRateViewRowImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(RoyaltyRateViewRowImpl obj, Object value) {
                obj.setCreatedDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(RoyaltyRateViewRowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(RoyaltyRateViewRowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(RoyaltyRateViewRowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(RoyaltyRateViewRowImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        DisplayRateType {
            public Object get(RoyaltyRateViewRowImpl obj) {
                return obj.getDisplayRateType();
            }

            public void put(RoyaltyRateViewRowImpl obj, Object value) {
                obj.setDisplayRateType((String)value);
            }
        }
        ,
        ContractRoyaltyRateTitleView {
            public Object get(RoyaltyRateViewRowImpl obj) {
                return obj.getContractRoyaltyRateTitleView();
            }

            public void put(RoyaltyRateViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        RoyaltyRateExceptionView {
            public Object get(RoyaltyRateViewRowImpl obj) {
                return obj.getRoyaltyRateExceptionView();
            }

            public void put(RoyaltyRateViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ContractMediaCodeLookup {
            public Object get(RoyaltyRateViewRowImpl obj) {
                return obj.getContractMediaCodeLookup();
            }

            public void put(RoyaltyRateViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ContractRoyaltyTypeLookup {
            public Object get(RoyaltyRateViewRowImpl obj) {
                return obj.getContractRoyaltyTypeLookup();
            }

            public void put(RoyaltyRateViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(RoyaltyRateViewRowImpl object);

        public abstract void put(RoyaltyRateViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int CONTRACTID = AttributesEnum.ContractId.index();
    public static final int MEDIA = AttributesEnum.Media.index();
    public static final int RATETYPE = AttributesEnum.RateType.index();
    public static final int ROYALTYRATE1 = AttributesEnum.RoyaltyRate1.index();
    public static final int EFFECTIVESTARTDATE = AttributesEnum.EffectiveStartDate.index();
    public static final int EFFECTIVEENDDATE = AttributesEnum.EffectiveEndDate.index();
    public static final int EXCEPTIONFLAG = AttributesEnum.ExceptionFlag.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int DISPLAYRATETYPE = AttributesEnum.DisplayRateType.index();
    public static final int CONTRACTROYALTYRATETITLEVIEW = AttributesEnum.ContractRoyaltyRateTitleView.index();
    public static final int ROYALTYRATEEXCEPTIONVIEW = AttributesEnum.RoyaltyRateExceptionView.index();
    public static final int CONTRACTMEDIACODELOOKUP = AttributesEnum.ContractMediaCodeLookup.index();
    public static final int CONTRACTROYALTYTYPELOOKUP = AttributesEnum.ContractRoyaltyTypeLookup.index();

    /**This is the default constructor (do not remove)
     */
    public RoyaltyRateViewRowImpl() {
    }

    /**Gets RoyaltyRate entity object.
     */
    public RoyaltyRateImpl getRoyaltyRate() {
        return (RoyaltyRateImpl)getEntity(0);
    }

    /**Gets the attribute value for ID using the alias name Id
     */
    public Number getId() {
        return (Number) getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as attribute value for ID using the alias name Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for CONTRACT_ID using the alias name ContractId
     */
    public Number getContractId() {
        return (Number) getAttributeInternal(CONTRACTID);
    }

    /**Sets <code>value</code> as attribute value for CONTRACT_ID using the alias name ContractId
     */
    public void setContractId(Number value) {
        setAttributeInternal(CONTRACTID, value);
    }

    /**Gets the attribute value for MEDIA using the alias name Media
     */
    public String getMedia() {
        return (String) getAttributeInternal(MEDIA);
    }

    /**Sets <code>value</code> as attribute value for MEDIA using the alias name Media
     */
    public void setMedia(String value) {
        setAttributeInternal(MEDIA, value);
    }

    /**Gets the attribute value for RATE_TYPE using the alias name RateType
     */
    public String getRateType() {
        return (String) getAttributeInternal(RATETYPE);
    }

    /**Sets <code>value</code> as attribute value for RATE_TYPE using the alias name RateType
     */
    public void setRateType(String value) {
        if("Percentage".equals(value))
            setDisplayRateType("%");
        else
            setDisplayRateType("");
        setAttributeInternal(RATETYPE, value);
    }

    /**Gets the attribute value for ROYALTY_RATE using the alias name RoyaltyRate1
     */
    public Number getRoyaltyRate1() {
        return (Number) getAttributeInternal(ROYALTYRATE1);
    }

    /**Sets <code>value</code> as attribute value for ROYALTY_RATE using the alias name RoyaltyRate1
     */
    public void setRoyaltyRate1(Number value) {
        setAttributeInternal(ROYALTYRATE1, value);
    }

    /**Gets the attribute value for EFFECTIVE_START_DATE using the alias name EffectiveStartDate
     */
    public Date getEffectiveStartDate() {
        return (Date) getAttributeInternal(EFFECTIVESTARTDATE);
    }

    /**Sets <code>value</code> as attribute value for EFFECTIVE_START_DATE using the alias name EffectiveStartDate
     */
    public void setEffectiveStartDate(Date value) {
        setAttributeInternal(EFFECTIVESTARTDATE, value);
    }

    /**Gets the attribute value for EFFECTIVE_END_DATE using the alias name EffectiveEndDate
     */
    public Date getEffectiveEndDate() {
        return (Date) getAttributeInternal(EFFECTIVEENDDATE);
    }

    /**Sets <code>value</code> as attribute value for EFFECTIVE_END_DATE using the alias name EffectiveEndDate
     */
    public void setEffectiveEndDate(Date value) {
        setAttributeInternal(EFFECTIVEENDDATE, value);
    }

    /**Gets the attribute value for EXCEPTION_FLAG using the alias name ExceptionFlag
     */
    public String getExceptionFlag() {
        return (String) getAttributeInternal(EXCEPTIONFLAG);
    }

    /**Sets <code>value</code> as attribute value for EXCEPTION_FLAG using the alias name ExceptionFlag
     */
    public void setExceptionFlag(String value) {
        setAttributeInternal(EXCEPTIONFLAG, value);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CREATED_DATE using the alias name CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }
    
    public void  setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }


    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**Gets the attribute value for ROYALTY_RATE using the alias name RoyaltyRate1_1_1
     */
    public Number getRoyaltyRate1_1_1() {
        return (Number) getAttributeInternal(ROYALTYRATE1_1_1);
    }

    /**Sets <code>value</code> as attribute value for ROYALTY_RATE using the alias name RoyaltyRate1_1_1
     */
    public void setRoyaltyRate1_1_1(Number value) {
        setAttributeInternal(ROYALTYRATE1_1_1, value);
    }


    /**Gets the attribute value for the calculated attribute DisplayRateType
     */
    public String getDisplayRateType() {
        return (String) getAttributeInternal(DISPLAYRATETYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DisplayRateType
     */
    public void setDisplayRateType(String value) {
        setAttributeInternal(DISPLAYRATETYPE, value);
    }


    /**Gets the associated <code>RowIterator</code> using master-detail link ContractRoyaltyRateTitleView
     */
    public RowIterator getContractRoyaltyRateTitleView() {
        return (RowIterator)getAttributeInternal(CONTRACTROYALTYRATETITLEVIEW);
    }

    /**Gets the associated <code>RowIterator</code> using master-detail link RoyaltyRateExceptionView
     */
    public RowIterator getRoyaltyRateExceptionView() {
        return (RowIterator)getAttributeInternal(ROYALTYRATEEXCEPTIONVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ContractMediaCodeLookup.
     */
    public RowSet getContractMediaCodeLookup() {
        return (RowSet)getAttributeInternal(CONTRACTMEDIACODELOOKUP);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ContractRoyaltyTypeLookup.
     */
    public RowSet getContractRoyaltyTypeLookup() {
        return (RowSet)getAttributeInternal(CONTRACTROYALTYTYPELOOKUP);
    }
}
