package com.pq.tracs.model.lookups;

import com.pq.tracs.model.dao.TracsView;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LookupCodeLookupImpl extends TracsView {
    /**This is the default constructor (do not remove)
     */
    public LookupCodeLookupImpl() {
    }

    /**Gets the bind variable value for code_set
     */
    public String getcode_set() {
        return (String)getNamedWhereClauseParam("code_set");
    }

    /**Sets <code>value</code> for bind variable code_set
     */
    public void setcode_set(String value) {
        setNamedWhereClauseParam("code_set", value);
    }
    
    
    protected void create() {
        super.create();
        setManageRowsByKey(true);
    }
}
