package com.pq.tracs.model.ro;

import com.pq.tracs.model.dao.TracsView;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DeliveryRightViewImpl extends TracsView {
    /**This is the default constructor (do not remove)
     */
    public DeliveryRightViewImpl() {
    }
}
