package com.pq.tracs.model.eo;

import com.pq.tracs.model.bo.ContentOwnerImpl;
import com.pq.tracs.model.bo.TracsBaseEntity;


import java.math.BigDecimal;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;

import oracle.jheadstart.util.DatabaseProcedure;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 15 14:00:08 EDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PrmOpportunityImpl extends TracsBaseEntity {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getId();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setId((Number)value);
            }
        }
        ,
        ContentOwnerId {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getContentOwnerId();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setContentOwnerId((Number)value);
            }
        }
        ,
        Name {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getName();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setName((String)value);
            }
        }
        ,
        Description {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getDescription();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        Summary {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getSummary();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setSummary((String)value);
            }
        }
        ,
        ProbabilityPct {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getProbabilityPct();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setProbabilityPct((Number)value);
            }
        }
        ,
        Priority {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getPriority();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setPriority((String)value);
            }
        }
        ,
        ExpectedPipelines {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getExpectedPipelines();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setExpectedPipelines((String)value);
            }
        }
        ,
        EstimatedCloseQuarter {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getEstimatedCloseQuarter();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setEstimatedCloseQuarter((String)value);
            }
        }
        ,
        AgreementReceivedDate {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getAgreementReceivedDate();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setAgreementReceivedDate((Date)value);
            }
        }
        ,
        ExclusivitySoughtObtained {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getExclusivitySoughtObtained();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setExclusivitySoughtObtained((String)value);
            }
        }
        ,
        AutoRenewal {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getAutoRenewal();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setAutoRenewal((String)value);
            }
        }
        ,
        OpportunityType {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getOpportunityType();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setOpportunityType((String)value);
            }
        }
        ,
        ReasonLost {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getReasonLost();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setReasonLost((String)value);
            }
        }
        ,
        DocumentSigned {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getDocumentSigned();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setDocumentSigned((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreatedDate {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setCreatedDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        CurrentStatus {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getCurrentStatus();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setCurrentStatus((String)value);
            }
        }
        ,
        SummonDeepIndexingFlag {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getSummonDeepIndexingFlag();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setSummonDeepIndexingFlag((String)value);
            }
        }
        ,
        CurrentPreStatus {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getCurrentPreStatus();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setCurrentPreStatus((String)value);
            }
        }
        ,
        CurrentCatalogingStatus {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getCurrentCatalogingStatus();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setCurrentCatalogingStatus((String)value);
            }
        }
        ,
        CurrentAgreementStatus {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getCurrentAgreementStatus();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setCurrentAgreementStatus((String)value);
            }
        }
        ,
        OpportunityNo {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getOpportunityNo();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setOpportunityNo((Number)value);
            }
        }
        ,
        AutoAddTargetsFlag {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getAutoAddTargetsFlag();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setAutoAddTargetsFlag((String)value);
            }
        }
        ,
        OpenAccessFlag {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getOpenAccessFlag();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setOpenAccessFlag((String)value);
            }
        }
        ,
        DocType {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getDocType();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setDocType((String)value);
            }
        }
        ,
        TraxActivityOpportunity {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getTraxActivityOpportunity();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PrmOpportunityContract {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getPrmOpportunityContract();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PrmOpportunityAgreementData {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getPrmOpportunityAgreementData();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PrmOpportunityTarget {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getPrmOpportunityTarget();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PrmOpportunityAttachment {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getPrmOpportunityAttachment();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PrmOpportunityProcessStatus {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getPrmOpportunityProcessStatus();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ContentOwner {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getContentOwner();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setContentOwner((ContentOwnerImpl)value);
            }
        }
        ,
        TraxPreResult {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getTraxPreResult();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PrmOpportuntiyStatus {
            public Object get(PrmOpportunityImpl obj) {
                return obj.getPrmOpportuntiyStatus();
            }

            public void put(PrmOpportunityImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(PrmOpportunityImpl object);

        public abstract void put(PrmOpportunityImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int CONTENTOWNERID = AttributesEnum.ContentOwnerId.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int SUMMARY = AttributesEnum.Summary.index();
    public static final int PROBABILITYPCT = AttributesEnum.ProbabilityPct.index();
    public static final int PRIORITY = AttributesEnum.Priority.index();
    public static final int EXPECTEDPIPELINES = AttributesEnum.ExpectedPipelines.index();
    public static final int ESTIMATEDCLOSEQUARTER = AttributesEnum.EstimatedCloseQuarter.index();
    public static final int AGREEMENTRECEIVEDDATE = AttributesEnum.AgreementReceivedDate.index();
    public static final int EXCLUSIVITYSOUGHTOBTAINED = AttributesEnum.ExclusivitySoughtObtained.index();
    public static final int AUTORENEWAL = AttributesEnum.AutoRenewal.index();
    public static final int OPPORTUNITYTYPE = AttributesEnum.OpportunityType.index();
    public static final int REASONLOST = AttributesEnum.ReasonLost.index();
    public static final int DOCUMENTSIGNED = AttributesEnum.DocumentSigned.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int CURRENTSTATUS = AttributesEnum.CurrentStatus.index();
    public static final int SUMMONDEEPINDEXINGFLAG = AttributesEnum.SummonDeepIndexingFlag.index();
    public static final int CURRENTPRESTATUS = AttributesEnum.CurrentPreStatus.index();
    public static final int CURRENTCATALOGINGSTATUS = AttributesEnum.CurrentCatalogingStatus.index();
    public static final int CURRENTAGREEMENTSTATUS = AttributesEnum.CurrentAgreementStatus.index();
    public static final int OPPORTUNITYNO = AttributesEnum.OpportunityNo.index();
    public static final int AUTOADDTARGETSFLAG = AttributesEnum.AutoAddTargetsFlag.index();
    public static final int OPENACCESSFLAG = AttributesEnum.OpenAccessFlag.index();
    public static final int DOCTYPE = AttributesEnum.DocType.index();
    public static final int TRAXACTIVITYOPPORTUNITY = AttributesEnum.TraxActivityOpportunity.index();
    public static final int PRMOPPORTUNITYCONTRACT = AttributesEnum.PrmOpportunityContract.index();
    public static final int PRMOPPORTUNITYAGREEMENTDATA = AttributesEnum.PrmOpportunityAgreementData.index();
    public static final int PRMOPPORTUNITYTARGET = AttributesEnum.PrmOpportunityTarget.index();
    public static final int PRMOPPORTUNITYATTACHMENT = AttributesEnum.PrmOpportunityAttachment.index();
    public static final int PRMOPPORTUNITYPROCESSSTATUS = AttributesEnum.PrmOpportunityProcessStatus.index();
    public static final int CONTENTOWNER = AttributesEnum.ContentOwner.index();
    public static final int TRAXPRERESULT = AttributesEnum.TraxPreResult.index();
    public static final int PRMOPPORTUNTIYSTATUS = AttributesEnum.PrmOpportuntiyStatus.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PrmOpportunityImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("com.pq.tracs.model.eo.PrmOpportunity");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the Id
     */
    public Number getId() {
        return (Number)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for ContentOwnerId, using the alias name ContentOwnerId.
     * @return the ContentOwnerId
     */
    public Number getContentOwnerId() {
        return (Number)getAttributeInternal(CONTENTOWNERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContentOwnerId.
     * @param value value to set the ContentOwnerId
     */
    public void setContentOwnerId(Number value) {
        setAttributeInternal(CONTENTOWNERID, value);
    }

    /**
     * Gets the attribute value for Name, using the alias name Name.
     * @return the Name
     */
    public String getName() {
        return (String)getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for Name.
     * @param value value to set the Name
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for Description, using the alias name Description.
     * @return the Description
     */
    public String getDescription() {
        return (String)getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Description.
     * @param value value to set the Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for Summary, using the alias name Summary.
     * @return the Summary
     */
    public String getSummary() {
        return (String)getAttributeInternal(SUMMARY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Summary.
     * @param value value to set the Summary
     */
    public void setSummary(String value) {
        setAttributeInternal(SUMMARY, value);
    }

    /**
     * Gets the attribute value for ProbabilityPct, using the alias name ProbabilityPct.
     * @return the ProbabilityPct
     */
    public Number getProbabilityPct() {
        return (Number)getAttributeInternal(PROBABILITYPCT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProbabilityPct.
     * @param value value to set the ProbabilityPct
     */
    public void setProbabilityPct(Number value) {
        setAttributeInternal(PROBABILITYPCT, value);
    }

    /**
     * Gets the attribute value for Priority, using the alias name Priority.
     * @return the Priority
     */
    public String getPriority() {
        return (String)getAttributeInternal(PRIORITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Priority.
     * @param value value to set the Priority
     */
    public void setPriority(String value) {
        setAttributeInternal(PRIORITY, value);
    }

    /**
     * Gets the attribute value for ExpectedPipelines, using the alias name ExpectedPipelines.
     * @return the ExpectedPipelines
     */
    public String getExpectedPipelines() {
        return (String)getAttributeInternal(EXPECTEDPIPELINES);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpectedPipelines.
     * @param value value to set the ExpectedPipelines
     */
    public void setExpectedPipelines(String value) {
        setAttributeInternal(EXPECTEDPIPELINES, value);
    }

    /**
     * Gets the attribute value for EstimatedCloseQuarter, using the alias name EstimatedCloseQuarter.
     * @return the EstimatedCloseQuarter
     */
    public String getEstimatedCloseQuarter() {
        return (String)getAttributeInternal(ESTIMATEDCLOSEQUARTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for EstimatedCloseQuarter.
     * @param value value to set the EstimatedCloseQuarter
     */
    public void setEstimatedCloseQuarter(String value) {
        setAttributeInternal(ESTIMATEDCLOSEQUARTER, value);
    }

    /**
     * Gets the attribute value for AgreementReceivedDate, using the alias name AgreementReceivedDate.
     * @return the AgreementReceivedDate
     */
    public Date getAgreementReceivedDate() {
        return (Date)getAttributeInternal(AGREEMENTRECEIVEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AgreementReceivedDate.
     * @param value value to set the AgreementReceivedDate
     */
    public void setAgreementReceivedDate(Date value) {
        setAttributeInternal(AGREEMENTRECEIVEDDATE, value);
    }

    /**
     * Gets the attribute value for ExclusivitySoughtObtained, using the alias name ExclusivitySoughtObtained.
     * @return the ExclusivitySoughtObtained
     */
    public String getExclusivitySoughtObtained() {
        return (String)getAttributeInternal(EXCLUSIVITYSOUGHTOBTAINED);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExclusivitySoughtObtained.
     * @param value value to set the ExclusivitySoughtObtained
     */
    public void setExclusivitySoughtObtained(String value) {
        setAttributeInternal(EXCLUSIVITYSOUGHTOBTAINED, value);
    }

    /**
     * Gets the attribute value for AutoRenewal, using the alias name AutoRenewal.
     * @return the AutoRenewal
     */
    public String getAutoRenewal() {
        return (String)getAttributeInternal(AUTORENEWAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for AutoRenewal.
     * @param value value to set the AutoRenewal
     */
    public void setAutoRenewal(String value) {
        setAttributeInternal(AUTORENEWAL, value);
    }

    /**
     * Gets the attribute value for OpportunityType, using the alias name OpportunityType.
     * @return the OpportunityType
     */
    public String getOpportunityType() {
        return (String)getAttributeInternal(OPPORTUNITYTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OpportunityType.
     * @param value value to set the OpportunityType
     */
    public void setOpportunityType(String value) {
        setAttributeInternal(OPPORTUNITYTYPE, value);
    }

    /**
     * Gets the attribute value for ReasonLost, using the alias name ReasonLost.
     * @return the ReasonLost
     */
    public String getReasonLost() {
        return (String)getAttributeInternal(REASONLOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReasonLost.
     * @param value value to set the ReasonLost
     */
    public void setReasonLost(String value) {
        setAttributeInternal(REASONLOST, value);
    }

    /**
     * Gets the attribute value for DocumentSigned, using the alias name DocumentSigned.
     * @return the DocumentSigned
     */
    public String getDocumentSigned() {
        return (String)getAttributeInternal(DOCUMENTSIGNED);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocumentSigned.
     * @param value value to set the DocumentSigned
     */
    public void setDocumentSigned(String value) {
        setAttributeInternal(DOCUMENTSIGNED, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the CreatedDate
     */
    public Date getCreatedDate() {
        return (Date)getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for CurrentStatus, using the alias name CurrentStatus.
     * @return the CurrentStatus
     */
    public String getCurrentStatus() {
        return (String)getAttributeInternal(CURRENTSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurrentStatus.
     * @param value value to set the CurrentStatus
     */
    public void setCurrentStatus(String value) {
        setAttributeInternal(CURRENTSTATUS, value);
    }

    /**
     * Gets the attribute value for SummonDeepIndexingFlag, using the alias name SummonDeepIndexingFlag.
     * @return the SummonDeepIndexingFlag
     */
    public String getSummonDeepIndexingFlag() {
        return (String)getAttributeInternal(SUMMONDEEPINDEXINGFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for SummonDeepIndexingFlag.
     * @param value value to set the SummonDeepIndexingFlag
     */
    public void setSummonDeepIndexingFlag(String value) {
        setAttributeInternal(SUMMONDEEPINDEXINGFLAG, value);
    }

    /**
     * Gets the attribute value for CurrentPreStatus, using the alias name CurrentPreStatus.
     * @return the CurrentPreStatus
     */
    public String getCurrentPreStatus() {
        return (String)getAttributeInternal(CURRENTPRESTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurrentPreStatus.
     * @param value value to set the CurrentPreStatus
     */
    public void setCurrentPreStatus(String value) {
        setAttributeInternal(CURRENTPRESTATUS, value);
    }

    /**
     * Gets the attribute value for CurrentCatalogingStatus, using the alias name CurrentCatalogingStatus.
     * @return the CurrentCatalogingStatus
     */
    public String getCurrentCatalogingStatus() {
        return (String)getAttributeInternal(CURRENTCATALOGINGSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurrentCatalogingStatus.
     * @param value value to set the CurrentCatalogingStatus
     */
    public void setCurrentCatalogingStatus(String value) {
        setAttributeInternal(CURRENTCATALOGINGSTATUS, value);
    }

    /**
     * Gets the attribute value for CurrentAgreementStatus, using the alias name CurrentAgreementStatus.
     * @return the CurrentAgreementStatus
     */
    public String getCurrentAgreementStatus() {
        return (String)getAttributeInternal(CURRENTAGREEMENTSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurrentAgreementStatus.
     * @param value value to set the CurrentAgreementStatus
     */
    public void setCurrentAgreementStatus(String value) {
        setAttributeInternal(CURRENTAGREEMENTSTATUS, value);
    }

    /**
     * Gets the attribute value for OpportunityNo, using the alias name OpportunityNo.
     * @return the OpportunityNo
     */
    public Number getOpportunityNo() {
        return (Number)getAttributeInternal(OPPORTUNITYNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for OpportunityNo.
     * @param value value to set the OpportunityNo
     */
    public void setOpportunityNo(Number value) {
        setAttributeInternal(OPPORTUNITYNO, value);
    }

    /**
     * Gets the attribute value for AutoAddTargetsFlag, using the alias name AutoAddTargetsFlag.
     * @return the AutoAddTargetsFlag
     */
    public String getAutoAddTargetsFlag() {
        return (String)getAttributeInternal(AUTOADDTARGETSFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for AutoAddTargetsFlag.
     * @param value value to set the AutoAddTargetsFlag
     */
    public void setAutoAddTargetsFlag(String value) {
        setAttributeInternal(AUTOADDTARGETSFLAG, value);
    }

    /**
     * Gets the attribute value for OpenAccessFlag, using the alias name OpenAccessFlag.
     * @return the OpenAccessFlag
     */
    public String getOpenAccessFlag() {
        return (String)getAttributeInternal(OPENACCESSFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for OpenAccessFlag.
     * @param value value to set the OpenAccessFlag
     */
    public void setOpenAccessFlag(String value) {
        setAttributeInternal(OPENACCESSFLAG, value);
    }

    /**
     * Gets the attribute value for DocType, using the alias name DocType.
     * @return the DocType
     */
    public String getDocType() {
        return (String)getAttributeInternal(DOCTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocType.
     * @param value value to set the DocType
     */
    public void setDocType(String value) {
        setAttributeInternal(DOCTYPE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTraxActivityOpportunity() {
        return (RowIterator)getAttributeInternal(TRAXACTIVITYOPPORTUNITY);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPrmOpportunityContract() {
        return (RowIterator)getAttributeInternal(PRMOPPORTUNITYCONTRACT);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPrmOpportunityAgreementData() {
        return (RowIterator)getAttributeInternal(PRMOPPORTUNITYAGREEMENTDATA);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPrmOpportunityTarget() {
        return (RowIterator)getAttributeInternal(PRMOPPORTUNITYTARGET);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPrmOpportunityAttachment() {
        return (RowIterator)getAttributeInternal(PRMOPPORTUNITYATTACHMENT);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPrmOpportunityProcessStatus() {
        return (RowIterator)getAttributeInternal(PRMOPPORTUNITYPROCESSSTATUS);
    }


    /**
     * @return the associated entity com.pq.tracs.model.bo.ContentOwnerImpl.
     */
    public ContentOwnerImpl getContentOwner() {
        return (ContentOwnerImpl)getAttributeInternal(CONTENTOWNER);
    }

    /**
     * Sets <code>value</code> as the associated entity com.pq.tracs.model.bo.ContentOwnerImpl.
     */
    public void setContentOwner(ContentOwnerImpl value) {
        setAttributeInternal(CONTENTOWNER, value);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getTraxPreResult() {
        return (RowIterator)getAttributeInternal(TRAXPRERESULT);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPrmOpportuntiyStatus() {
        return (RowIterator)getAttributeInternal(PRMOPPORTUNTIYSTATUS);
    }


    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number id) {
        return new Key(new Object[]{id});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    public void create(AttributeList attributeList) {
        super.create(attributeList);
        this.setCurrentStatus("00");
        this.setCurrentPreStatus("New");
        this.setCurrentCatalogingStatus("New");
        this.setCurrentAgreementStatus("New");
      try {
          SequenceImpl seq =
              new SequenceImpl("PRM_OPPORTUNITY_NO_SEQ", getDBTransaction());
          this.setOpportunityNo(seq.getSequenceNumber()); 

      } catch (Exception e1) {
          System.out.println("*******************Exception while creating opportunity number***********************");
          System.out.println("Error :" + e1.toString());
          //throw new JboException("Invalid primary key value.");
      }

    }

    private void linkTitles() {
        try {
            Number oppId = this.getId();
            Number acctId = this.getContentOwnerId();

            String uName = this.getLoginUserId();

            DatabaseProcedure targetTitlesToProductsProc =
                DatabaseProcedure.define("procedure pk_prm_opportunity_methods.target_autoadd_titles" +
                                         "( p_opp_id in number, p_acct_id in number, p_username varchar2, p_status_code out number, p_status_message out varchar2)");
            DatabaseProcedure.Result result =
                targetTitlesToProductsProc.call(this.getDBTransaction(), oppId,
                                                acctId, uName);

            String statusMessage =
                (String)result.getOutputValue("p_status_message");
            BigDecimal statusCode =
                (BigDecimal)result.getOutputValue("p_status_code");

            if (statusCode.compareTo(new BigDecimal(0)) == 0) {
                statusMessage = "Targeting Complete.";
            } else {
                FacesContext.getCurrentInstance().addMessage(null,
                                                             new FacesMessage(statusMessage));
            }
        } catch (Exception ex) {
            FacesContext.getCurrentInstance().addMessage(null,
                                                         new FacesMessage(ex.getMessage()));
        }

    }

    public void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);

        if (operation == DML_INSERT) {

            if (this.getAutoAddTargetsFlag().equalsIgnoreCase("Y")) {
              linkTitles();
            }

        }

    }
    
    
    
    

}
