package com.pq.tracs.model.eo;

import com.pq.tracs.model.bo.TracsBaseEntity;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 02 14:50:36 EST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PrmOpportunityTargetImpl extends TracsBaseEntity {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(PrmOpportunityTargetImpl obj) {
                return obj.getId();
            }

            public void put(PrmOpportunityTargetImpl obj, Object value) {
                obj.setId((Number)value);
            }
        }
        ,
        PrmOpportunityId {
            public Object get(PrmOpportunityTargetImpl obj) {
                return obj.getPrmOpportunityId();
            }

            public void put(PrmOpportunityTargetImpl obj, Object value) {
                obj.setPrmOpportunityId((Number)value);
            }
        }
        ,
        PrmTargetedProductTitleId {
            public Object get(PrmOpportunityTargetImpl obj) {
                return obj.getPrmTargetedProductTitleId();
            }

            public void put(PrmOpportunityTargetImpl obj, Object value) {
                obj.setPrmTargetedProductTitleId((Number)value);
            }
        }
        ,
        AddedDate {
            public Object get(PrmOpportunityTargetImpl obj) {
                return obj.getAddedDate();
            }

            public void put(PrmOpportunityTargetImpl obj, Object value) {
                obj.setAddedDate((Date)value);
            }
        }
        ,
        RemovedDate {
            public Object get(PrmOpportunityTargetImpl obj) {
                return obj.getRemovedDate();
            }

            public void put(PrmOpportunityTargetImpl obj, Object value) {
                obj.setRemovedDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(PrmOpportunityTargetImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(PrmOpportunityTargetImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreatedDate {
            public Object get(PrmOpportunityTargetImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(PrmOpportunityTargetImpl obj, Object value) {
                obj.setCreatedDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(PrmOpportunityTargetImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(PrmOpportunityTargetImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(PrmOpportunityTargetImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(PrmOpportunityTargetImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        TargetStatus {
            public Object get(PrmOpportunityTargetImpl obj) {
                return obj.getTargetStatus();
            }

            public void put(PrmOpportunityTargetImpl obj, Object value) {
                obj.setTargetStatus((String)value);
            }
        }
        ,
        PrmOpportunity {
            public Object get(PrmOpportunityTargetImpl obj) {
                return obj.getPrmOpportunity();
            }

            public void put(PrmOpportunityTargetImpl obj, Object value) {
                obj.setPrmOpportunity((PrmOpportunityImpl)value);
            }
        }
        ,
        PrmTargetedProductTitle {
            public Object get(PrmOpportunityTargetImpl obj) {
                return obj.getPrmTargetedProductTitle();
            }

            public void put(PrmOpportunityTargetImpl obj, Object value) {
                obj.setPrmTargetedProductTitle((PrmTargetedProductTitleImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(PrmOpportunityTargetImpl object);

        public abstract void put(PrmOpportunityTargetImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int ID = AttributesEnum.Id.index();
    public static final int PRMOPPORTUNITYID = AttributesEnum.PrmOpportunityId.index();
    public static final int PRMTARGETEDPRODUCTTITLEID = AttributesEnum.PrmTargetedProductTitleId.index();
    public static final int ADDEDDATE = AttributesEnum.AddedDate.index();
    public static final int REMOVEDDATE = AttributesEnum.RemovedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int TARGETSTATUS = AttributesEnum.TargetStatus.index();
    public static final int PRMOPPORTUNITY = AttributesEnum.PrmOpportunity.index();
    public static final int PRMTARGETEDPRODUCTTITLE = AttributesEnum.PrmTargetedProductTitle.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PrmOpportunityTargetImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("com.pq.tracs.model.eo.PrmOpportunityTarget");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the Id
     */
    public Number getId() {
        return (Number)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for PrmOpportunityId, using the alias name PrmOpportunityId.
     * @return the PrmOpportunityId
     */
    public Number getPrmOpportunityId() {
        return (Number)getAttributeInternal(PRMOPPORTUNITYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PrmOpportunityId.
     * @param value value to set the PrmOpportunityId
     */
    public void setPrmOpportunityId(Number value) {
        setAttributeInternal(PRMOPPORTUNITYID, value);
    }

    /**
     * Gets the attribute value for PrmTargetedProductTitleId, using the alias name PrmTargetedProductTitleId.
     * @return the PrmTargetedProductTitleId
     */
    public Number getPrmTargetedProductTitleId() {
        return (Number)getAttributeInternal(PRMTARGETEDPRODUCTTITLEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PrmTargetedProductTitleId.
     * @param value value to set the PrmTargetedProductTitleId
     */
    public void setPrmTargetedProductTitleId(Number value) {
        setAttributeInternal(PRMTARGETEDPRODUCTTITLEID, value);
    }

    /**
     * Gets the attribute value for AddedDate, using the alias name AddedDate.
     * @return the AddedDate
     */
    public Date getAddedDate() {
        return (Date)getAttributeInternal(ADDEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AddedDate.
     * @param value value to set the AddedDate
     */
    public void setAddedDate(Date value) {
        setAttributeInternal(ADDEDDATE, value);
    }

    /**
     * Gets the attribute value for RemovedDate, using the alias name RemovedDate.
     * @return the RemovedDate
     */
    public Date getRemovedDate() {
        return (Date)getAttributeInternal(REMOVEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RemovedDate.
     * @param value value to set the RemovedDate
     */
    public void setRemovedDate(Date value) {
        setAttributeInternal(REMOVEDDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the CreatedDate
     */
    public Date getCreatedDate() {
        return (Date)getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for TargetStatus, using the alias name TargetStatus.
     * @return the TargetStatus
     */
    public String getTargetStatus() {
        return (String)getAttributeInternal(TARGETSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for TargetStatus.
     * @param value value to set the TargetStatus
     */
    public void setTargetStatus(String value) {
        setAttributeInternal(TARGETSTATUS, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity PrmOpportunityImpl.
     */
    public PrmOpportunityImpl getPrmOpportunity() {
        return (PrmOpportunityImpl)getAttributeInternal(PRMOPPORTUNITY);
    }

    /**
     * Sets <code>value</code> as the associated entity PrmOpportunityImpl.
     */
    public void setPrmOpportunity(PrmOpportunityImpl value) {
        setAttributeInternal(PRMOPPORTUNITY, value);
    }

    /**
     * @return the associated entity com.pq.tracs.model.eo.PrmBaseEntity.
     */
    public PrmTargetedProductTitleImpl getPrmTargetedProductTitle() {
        return (PrmTargetedProductTitleImpl)getAttributeInternal(PRMTARGETEDPRODUCTTITLE);
    }

    /**
     * Sets <code>value</code> as the associated entity com.pq.tracs.model.eo.PrmBaseEntity.
     */
    public void setPrmTargetedProductTitle(PrmTargetedProductTitleImpl value) {
        setAttributeInternal(PRMTARGETEDPRODUCTTITLE, value);
    }


    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number id) {
        return new Key(new Object[]{id});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    public void create(AttributeList attributeList) {
        super.create(attributeList);
        this.setAddedDate(new Date(Date.getCurrentDate()));
    }

    protected void prepareForDML(int operation, TransactionEvent e) {
        super.prepareForDML(operation, e);
        try {
            if (operation == DML_INSERT || operation == DML_UPDATE) {
                RowIterator indextIter =
                    this.getPrmTargetedProductTitle().getTraxTitle().getTraxTitleIndexInclusion();

                TraxTitleIndexInclusionImpl index = null;
                PrmOpportunityImpl opp = this.getPrmOpportunity();

                index = (TraxTitleIndexInclusionImpl)indextIter.next();
                if ("DOAJ".equalsIgnoreCase(index.getIndexName())) {
                    opp.setOpenAccessFlag("Y");
                }
            }
        }
        catch (Exception efg) {

        }
    }
}
