package com.pq.tracs.model.eo;

import com.pq.tracs.model.bo.TracsBaseEntity;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 05 20:36:47 EDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TraxOvrAttributeTypeImpl extends TracsBaseEntity {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(TraxOvrAttributeTypeImpl obj) {
                return obj.getId();
            }

            public void put(TraxOvrAttributeTypeImpl obj, Object value) {
                obj.setId((Number)value);
            }
        }
        ,
        ContentSource {
            public Object get(TraxOvrAttributeTypeImpl obj) {
                return obj.getContentSource();
            }

            public void put(TraxOvrAttributeTypeImpl obj, Object value) {
                obj.setContentSource((String)value);
            }
        }
        ,
        AttributeType {
            public Object get(TraxOvrAttributeTypeImpl obj) {
                return obj.getAttributeType();
            }

            public void put(TraxOvrAttributeTypeImpl obj, Object value) {
                obj.setAttributeType((String)value);
            }
        }
        ,
        DataType {
            public Object get(TraxOvrAttributeTypeImpl obj) {
                return obj.getDataType();
            }

            public void put(TraxOvrAttributeTypeImpl obj, Object value) {
                obj.setDataType((String)value);
            }
        }
        ,
        CodeSet {
            public Object get(TraxOvrAttributeTypeImpl obj) {
                return obj.getCodeSet();
            }

            public void put(TraxOvrAttributeTypeImpl obj, Object value) {
                obj.setCodeSet((String)value);
            }
        }
        ,
        TrmsValue {
            public Object get(TraxOvrAttributeTypeImpl obj) {
                return obj.getTrmsValue();
            }

            public void put(TraxOvrAttributeTypeImpl obj, Object value) {
                obj.setTrmsValue((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(TraxOvrAttributeTypeImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(TraxOvrAttributeTypeImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreatedDate {
            public Object get(TraxOvrAttributeTypeImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(TraxOvrAttributeTypeImpl obj, Object value) {
                obj.setCreatedDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(TraxOvrAttributeTypeImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(TraxOvrAttributeTypeImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(TraxOvrAttributeTypeImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(TraxOvrAttributeTypeImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        TraxOvrAttribute {
            public Object get(TraxOvrAttributeTypeImpl obj) {
                return obj.getTraxOvrAttribute();
            }

            public void put(TraxOvrAttributeTypeImpl obj, Object value) {
                obj.setTraxOvrAttribute((TraxOvrAttributeImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(TraxOvrAttributeTypeImpl object);

        public abstract void put(TraxOvrAttributeTypeImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int CONTENTSOURCE = AttributesEnum.ContentSource.index();
    public static final int ATTRIBUTETYPE = AttributesEnum.AttributeType.index();
    public static final int DATATYPE = AttributesEnum.DataType.index();
    public static final int CODESET = AttributesEnum.CodeSet.index();
    public static final int TRMSVALUE = AttributesEnum.TrmsValue.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int TRAXOVRATTRIBUTE = AttributesEnum.TraxOvrAttribute.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TraxOvrAttributeTypeImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("com.pq.tracs.model.eo.TraxOvrAttributeType");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the Id
     */
    public Number getId() {
        return (Number)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for ContentSource, using the alias name ContentSource.
     * @return the ContentSource
     */
    public String getContentSource() {
        return (String)getAttributeInternal(CONTENTSOURCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContentSource.
     * @param value value to set the ContentSource
     */
    public void setContentSource(String value) {
        setAttributeInternal(CONTENTSOURCE, value);
    }

    /**
     * Gets the attribute value for AttributeType, using the alias name AttributeType.
     * @return the AttributeType
     */
    public String getAttributeType() {
        return (String)getAttributeInternal(ATTRIBUTETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttributeType.
     * @param value value to set the AttributeType
     */
    public void setAttributeType(String value) {
        setAttributeInternal(ATTRIBUTETYPE, value);
    }

    /**
     * Gets the attribute value for DataType, using the alias name DataType.
     * @return the DataType
     */
    public String getDataType() {
        return (String)getAttributeInternal(DATATYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DataType.
     * @param value value to set the DataType
     */
    public void setDataType(String value) {
        setAttributeInternal(DATATYPE, value);
    }

    /**
     * Gets the attribute value for CodeSet, using the alias name CodeSet.
     * @return the CodeSet
     */
    public String getCodeSet() {
        return (String)getAttributeInternal(CODESET);
    }

    /**
     * Sets <code>value</code> as the attribute value for CodeSet.
     * @param value value to set the CodeSet
     */
    public void setCodeSet(String value) {
        setAttributeInternal(CODESET, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the CreatedDate
     */
    public Date getCreatedDate() {
        return (Date)getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for TrmsValue, using the alias name TrmsValue.
     * @return the TrmsValue
     */
    public String getTrmsValue() {
        return (String)getAttributeInternal(TRMSVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TrmsValue.
     * @param value value to set the TrmsValue
     */
    public void setTrmsValue(String value) {
        setAttributeInternal(TRMSVALUE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity TraxOvrAttributeImpl.
     */
    public TraxOvrAttributeImpl getTraxOvrAttribute() {
        return (TraxOvrAttributeImpl)getAttributeInternal(TRAXOVRATTRIBUTE);
    }

    /**
     * Sets <code>value</code> as the associated entity TraxOvrAttributeImpl.
     */
    public void setTraxOvrAttribute(TraxOvrAttributeImpl value) {
        setAttributeInternal(TRAXOVRATTRIBUTE, value);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number id) {
        return new Key(new Object[]{id});
    }


}
