package com.pq.tracs.model.ro;

import com.pq.tracs.model.dao.TracsView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 13 13:58:44 EDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OpportunitiesDashboardViewImpl extends TracsView {
    /**
     * This is the default constructor (do not remove).
     */
    public OpportunitiesDashboardViewImpl() {
    }

    /**
     * Returns the bind variable value for uname.
     * @return bind variable value for uname
     */
    public String getuname() {
        return (String)getNamedWhereClauseParam("uname");
    }

    /**
     * Sets <code>value</code> for bind variable uname.
     * @param value value to bind as uname
     */
    public void setuname(String value) {
        setNamedWhereClauseParam("uname", value);
    }
}
