package com.pq.tracs.model.custom.dao;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GroupPermissionsViewImpl extends ViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public GroupPermissionsViewImpl() {
    }
}
